# Generated by Django 4.1.4 on 2022-12-09 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('actualizar', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(upload_to='pdfs/')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=1000000)),
                ('categoria', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=20)),
                ('likes', models.IntegerField(default=0)),
                ('vistas', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
        ),
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('actualizar', models.DateTimeField(auto_now=True)),
                ('canal_code', models.CharField(default='000aaa', editable=False, max_length=6)),
                ('canal_name', models.CharField(default='Grupo de Amigos', max_length=100)),
            ],
            options={
                'verbose_name': 'Canales',
                'verbose_name_plural': 'Canales',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('actualizar', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=100)),
                ('user_image', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('actualizar', models.DateTimeField(auto_now=True)),
                ('ms_text', models.CharField(max_length=1000000)),
                ('ms_user', models.CharField(max_length=1000000)),
                ('ms_canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Repositorio.canal')),
            ],
            options={
                'verbose_name': 'Mensajes',
                'verbose_name_plural': 'Mensajes',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('actualizar', models.DateTimeField(auto_now=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Repositorio.canal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Repositorio.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('actualizar', models.DateTimeField(auto_now=True)),
                ('cm_texto', models.CharField(max_length=1000000)),
                ('cm_archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Repositorio.archivo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='canal',
            name='canal_users',
            field=models.ManyToManyField(blank=True, through='Repositorio.Membership', to='Repositorio.usuario'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='canal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Repositorio.canal'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Repositorio.usuario'),
        ),
    ]
