# Generated by Django 4.1.4 on 2022-12-09 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Repositorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
    ]
